service: download-boilerplate-code

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  create:
    handler: handlers/boilerplatecode.create
